# Generated by Django 5.0.6 on 2024-06-27 19:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название привычки')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место выполнения привычки')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время выполнения привычки')),
                ('action', models.CharField(max_length=100, verbose_name='Действие привычки')),
                ('pleasant_habit', models.BooleanField(default=True, verbose_name='Признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('ежедневно', 'ежедневно'), ('еженедельно', 'еженедельно')], default='ежедневно', max_length=20, verbose_name='Периодичность привычки')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('time_required', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Время на выполнение привычки')),
                ('public_visibility', models.BooleanField(default=True, verbose_name='Признак публичной привычки')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
