# Generated by Django 5.0.6 on 2024-06-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="name",
        ),
    ]
