# Generated by Django 5.0.6 on 2024-06-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_remove_habit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    (1, "Ежедневно"),
                    (2, "Каждые 2 дня"),
                    (3, "Каждые 3 дня"),
                    (4, "Каждые 4 дня"),
                    (5, "Каждые 5 дней"),
                    (6, "Каждые 6 дней"),
                    (7, "Еженедельно"),
                ],
                default=1,
                max_length=20,
                verbose_name="Периодичность привычки",
            ),
        ),
    ]
